version: '3.8'
services:
  datadog-agent:
    image: datadog/agent:7.56.0
    container_name: datadog-agent
    restart: always
    environment:
      - DD_API_KEY=${DD_API_KEY}  # Set this in .env or export
      - DD_SITE=us5.datadoghq.com     # Or your region, e.g., datadoghq.eu
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENABLED=true
      - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317
      - DD_LOGS_ENABLED=true
      - DD_APM_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:datadog-agent"
    ports:
      - "8126:8126/udp"  # For direct ddtrace if needed
      - "4317:4317"      # OTLP gRPC
      - "4318:4318"      # OTLP HTTP (optional)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # For container metrics
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro